---

- name: install nginx
  apt:
    pkg: nginx-light

- name: disable server_tokens
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^\\s*#? ?server_tokens"
    line: "server_tokens off;"
  register: config

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: config.changed

- name: delete index.nginx-debian.html
  file:
    path: "{{ www }}/index.nginx-debian.html"
    state: absent

- name: install index.html
  template:
    src: index.html
    dest: "{{ www }}/index.html"

- name: install robots.txt
  copy:
    src: robots.txt
    dest: "{{ www }}/robots.txt"

...
