#!/usr/bin/env python
import requests
import csv

url = 'https://torstatus.blutmagie.de/query_export.php/Tor_query_EXPORT.csv'
r = requests.get(url, stream=True)

def wrap(f):
    for x in f:
        yield str(x, 'utf-8')

for x in csv.DictReader(wrap(r.raw)):
    ip = x['IP Address']
    orport = x['ORPort']
    dirport = x['DirPort']

    for port in [orport, dirport]:
        if ip and port:
            try:
                print('%s:%d' % (ip, int(port)))
            except ValueError:
                pass
